/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grupox.pokemonv.view;

import javax.swing.JFrame;

/**
 *
 * @author alulab14
 */
public class Battle extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public Battle() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        setTitle("Batalla Pokemon");
        setLocation(400, 350);
        jProgressBar2.setValue(100);
        jProgressBar3.setValue(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTNpassword = new javax.swing.JButton();
        BTNpassword1 = new javax.swing.JButton();
        BTNpassword2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 400));
        getContentPane().setLayout(null);

        BTNpassword.setBackground(new java.awt.Color(34, 34, 149));
        BTNpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNpassword.setForeground(new java.awt.Color(255, 255, 255));
        BTNpassword.setText("Retirarse");
        BTNpassword.setAlignmentY(0.2F);
        BTNpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(BTNpassword);
        BTNpassword.setBounds(410, 320, 101, 33);

        BTNpassword1.setBackground(new java.awt.Color(0, 0, 0));
        BTNpassword1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNpassword1.setForeground(new java.awt.Color(255, 255, 255));
        BTNpassword1.setText("Atacar");
        BTNpassword1.setAlignmentY(0.2F);
        BTNpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNpassword1ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNpassword1);
        BTNpassword1.setBounds(340, 270, 106, 33);

        BTNpassword2.setBackground(new java.awt.Color(32, 102, 55));
        BTNpassword2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNpassword2.setForeground(new java.awt.Color(255, 255, 255));
        BTNpassword2.setText("Mochila");
        BTNpassword2.setAlignmentY(0.2F);
        BTNpassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNpassword2ActionPerformed(evt);
            }
        });
        getContentPane().add(BTNpassword2);
        BTNpassword2.setBounds(460, 270, 106, 33);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VIDA BULBASAUR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 30, 130, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VIDA PIKACHU");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 130, 120, 14);

        jProgressBar2.setBackground(new java.awt.Color(0, 204, 102));
        jProgressBar2.setName("barBulba"); // NOI18N
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(380, 60, 200, 20);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(610, 400, 146, 20);

        jProgressBar3.setBackground(new java.awt.Color(0, 204, 102));
        jProgressBar3.setName("barPika"); // NOI18N
        getContentPane().add(jProgressBar3);
        jProgressBar3.setBounds(20, 150, 200, 20);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 600, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNpassword1ActionPerformed
        // TODO add your handling code here:
        int n = jProgressBar2.getValue();
        n -= 20;
        jProgressBar2.setValue(n);
        if (n==0){
            new DefeatMessage().setVisible(true);
        }
        
    }//GEN-LAST:event_BTNpassword1ActionPerformed

    private void BTNpassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNpassword2ActionPerformed

    }//GEN-LAST:event_BTNpassword2ActionPerformed

    private void BTNpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Battle().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNpassword;
    private javax.swing.JButton BTNpassword1;
    private javax.swing.JButton BTNpassword2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    // End of variables declaration//GEN-END:variables
}
