package com.grupox.pokemonv.view;

import com.grupox.pokemonv.controller.Game;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;


public class Login extends javax.swing.JFrame {
    
    /**
     * Creates new form FrmLogin
     */
    public Login() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        setTitle("Login");
        setLocation(550, 350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTNusername = new javax.swing.JButton();
        BTNpassword = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        BTNpassword1 = new javax.swing.JButton();
        BTNpassword2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BTNusername.setBackground(new java.awt.Color(34, 34, 149));
        BTNusername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNusername.setForeground(new java.awt.Color(255, 255, 255));
        BTNusername.setText("Username");
        BTNusername.setAlignmentY(0.2F);

        BTNpassword.setBackground(new java.awt.Color(34, 34, 149));
        BTNpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNpassword.setForeground(new java.awt.Color(255, 255, 255));
        BTNpassword.setText("Password");
        BTNpassword.setAlignmentY(0.2F);

        jTextPane1.setBackground(new java.awt.Color(41, 40, 32));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        BTNpassword1.setBackground(new java.awt.Color(53, 148, 0));
        BTNpassword1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNpassword1.setForeground(new java.awt.Color(255, 255, 255));
        BTNpassword1.setText("Login");
        BTNpassword1.setAlignmentY(0.2F);
        BTNpassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNpassword1ActionPerformed(evt);
            }
        });

        BTNpassword2.setBackground(new java.awt.Color(32, 102, 55));
        BTNpassword2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNpassword2.setForeground(new java.awt.Color(255, 255, 255));
        BTNpassword2.setText("Register");
        BTNpassword2.setAlignmentY(0.2F);
        BTNpassword2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNpassword2ActionPerformed(evt);
            }
        });

        jPasswordField1.setText("jPasswordField1");

        jLabel2.setIcon(new javax.swing.ImageIcon("T:\\LP2\\Alejandro\\LP2\\LP2Draw\\res\\login\\fasss.png")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(BTNusername))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(BTNpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(BTNpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(BTNpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNusername)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNpassword)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNpassword1)
                            .addComponent(BTNpassword2)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNpassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNpassword1ActionPerformed
        setVisible(false);
        Game game = new Game();
        game.start();
//        dispose();
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));

    }//GEN-LAST:event_BTNpassword1ActionPerformed

    private void BTNpassword2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNpassword2ActionPerformed
        Register regis = new Register();
        regis.setVisible(true);
    }//GEN-LAST:event_BTNpassword2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNpassword;
    private javax.swing.JButton BTNpassword1;
    private javax.swing.JButton BTNpassword2;
    private javax.swing.JButton BTNusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
