package com.grupox.pokemonv.view;

import com.grupox.pokemonv.model.Pokemon;
import com.grupox.pokemonv.model.Pokemon.TypeP;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;

/**
 *
 * @author alulab14
 */
public class Pokemons extends javax.swing.JFrame {

    /**
     * Creates new form PokemonsPanel
     */
    //Image harambesRevenge;
    private ArrayList<Pokemon> listaPokemones;
    int indice=0;
    public Pokemons() {
        initComponents();
        
        jLabel2.setIcon(new javax.swing.ImageIcon("res\\pokemons\\fondoPokemons2.png")); // Set a relative path (auto-generated SUCKS)
        
        listaPokemones = new ArrayList<>();
        TypeP tipoE = TypeP.Earth;
        TypeP tipoF = TypeP.Fire;
        TypeP tipoWa = TypeP.Water;
        TypeP tipoWi = TypeP.Wind;
        Pokemon pok1 = new Pokemon(1,10,20,30,"Bulbasaur",tipoE);
        Pokemon pok2 = new Pokemon(4,30,20,46,"Charmander",tipoF);
        Pokemon pok3 = new Pokemon(7,50,10,30,"Squirtle",tipoWa);
        Pokemon pok4 = new Pokemon(12,60,22,44,"Butterfree",tipoWi);
        listaPokemones.add(pok1);
        listaPokemones.add(pok2);
        listaPokemones.add(pok3);
        listaPokemones.add(pok4);
        verPokemones();
    }

    public void verPokemones(){
        Pokemon pok = listaPokemones.get(0+indice);
        txtPokemon1.setText(pok.getName());
        String vida = String.valueOf(pok.getLife());
        txtPokemonVida1.setText(vida);
        String nombre = String.valueOf(pok.getId());
        String ruta = "res/pokemons/" + nombre+".png";
        //ImageIcon img1 = new ImageIcon(getClass().getResource(ruta));
        ImageIcon img1 = new ImageIcon(ruta);
        ImageIcon icono = new ImageIcon(img1.getImage().getScaledInstance(jlImgPokemon1.getWidth(),jlImgPokemon1.getHeight(), Image.SCALE_DEFAULT));
        jlImgPokemon1.setIcon(icono);

        Pokemon pok2 = listaPokemones.get(1+indice);
        txtPokemon2.setText(pok2.getName());
        String vida2 = String.valueOf(pok2.getLife());
        txtPokemonVida2.setText(vida2);
        String nombre2 = String.valueOf(pok2.getId());
        String ruta2 = "res/pokemons/" + nombre2+".png";
        //ImageIcon img2 = new ImageIcon(getClass().getResource(ruta2));
        ImageIcon img2 = new ImageIcon(ruta2);
        ImageIcon icono2 = new ImageIcon(img2.getImage().getScaledInstance(jlImgPokemon2.getWidth(),jlImgPokemon2.getHeight(), Image.SCALE_DEFAULT));
        jlImgPokemon2.setIcon(icono2);
        
        Pokemon pok3 = listaPokemones.get(2+indice);
        txtPokemon3.setText(pok3.getName());
        String vida3 = String.valueOf(pok3.getLife());
        txtPokemonVida3.setText(vida3);
        String nombre3 = String.valueOf(pok3.getId());
        String ruta3 = "res/pokemons/" + nombre3+".png";
        //ImageIcon img3 = new ImageIcon(getClass().getResource(ruta3));
        ImageIcon img3 = new ImageIcon(ruta3);
        ImageIcon icono3 = new ImageIcon(img3.getImage().getScaledInstance(jlImgPokemon3.getWidth(),jlImgPokemon3.getHeight(), Image.SCALE_DEFAULT));
        jlImgPokemon3.setIcon(icono3);
        
        Pokemon pok4 = listaPokemones.get(3+indice);
        txtPokemon4.setText(pok4.getName());
        String vida4 = String.valueOf(pok4.getLife());
        txtPokemonVida4.setText(vida4);
        String nombre4 = String.valueOf(pok4.getId());
        String ruta4 = "res/pokemons/" + nombre4+".png";
        //ImageIcon img4 = new ImageIcon(getClass().getResource(ruta4));
        ImageIcon img4 = new ImageIcon(ruta4);
        ImageIcon icono4 = new ImageIcon(img4.getImage().getScaledInstance(jlImgPokemon4.getWidth(),jlImgPokemon4.getHeight(), Image.SCALE_DEFAULT));
        jlImgPokemon4.setIcon(icono4);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPokemonSelected = new javax.swing.JPanel();
        txtPokemonSNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPokemonSAtaque = new javax.swing.JTextField();
        txtPokemonSDefensa = new javax.swing.JTextField();
        txtPokemonSVida = new javax.swing.JTextField();
        txtPokemonSTipo = new javax.swing.JTextField();
        jlPokSelectedImg = new javax.swing.JLabel();
        jpPokemon1 = new javax.swing.JPanel();
        txtPokemonVida1 = new javax.swing.JTextField();
        txtPokemon1 = new javax.swing.JTextField();
        jlImgPokemon1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpPokemon2 = new javax.swing.JPanel();
        txtPokemon2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jlImgPokemon2 = new javax.swing.JLabel();
        txtPokemonVida2 = new javax.swing.JTextField();
        jpPokemon3 = new javax.swing.JPanel();
        txtPokemon3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPokemonVida3 = new javax.swing.JTextField();
        jlImgPokemon3 = new javax.swing.JLabel();
        jpPokemon4 = new javax.swing.JPanel();
        txtPokemon4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPokemonVida4 = new javax.swing.JTextField();
        jlImgPokemon4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpPokemonSelected.setBackground(new java.awt.Color(51, 204, 255));

        txtPokemonSNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemonSNombreActionPerformed(evt);
            }
        });

        jLabel4.setText("ATAQUE:");

        jLabel5.setText("DEFENSA:");

        jLabel6.setText("VIDA:");

        jLabel7.setText("NOMBRE:");

        jLabel8.setText("TIPO:");

        txtPokemonSAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemonSAtaqueActionPerformed(evt);
            }
        });

        txtPokemonSDefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemonSDefensaActionPerformed(evt);
            }
        });

        txtPokemonSVida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemonSVidaActionPerformed(evt);
            }
        });

        txtPokemonSTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemonSTipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPokemonSelectedLayout = new javax.swing.GroupLayout(jpPokemonSelected);
        jpPokemonSelected.setLayout(jpPokemonSelectedLayout);
        jpPokemonSelectedLayout.setHorizontalGroup(
            jpPokemonSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPokemonSelectedLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpPokemonSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPokemonSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPokemonSelectedLayout.createSequentialGroup()
                        .addGroup(jpPokemonSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPokemonSVida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(txtPokemonSDefensa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPokemonSAtaque, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlPokSelectedImg, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                    .addGroup(jpPokemonSelectedLayout.createSequentialGroup()
                        .addGroup(jpPokemonSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPokemonSNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(txtPokemonSTipo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpPokemonSelectedLayout.setVerticalGroup(
            jpPokemonSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPokemonSelectedLayout.createSequentialGroup()
                .addGroup(jpPokemonSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPokemonSelectedLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jpPokemonSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPokemonSAtaque, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpPokemonSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPokemonSDefensa, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpPokemonSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPokemonSVida)))
                    .addGroup(jpPokemonSelectedLayout.createSequentialGroup()
                        .addContainerGap(24, Short.MAX_VALUE)
                        .addComponent(jlPokSelectedImg, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPokemonSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPokemonSNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPokemonSelectedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPokemonSTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        jpPokemon1.setBackground(new java.awt.Color(0, 204, 204));
        jpPokemon1.setName(""); // NOI18N

        txtPokemonVida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemonVida1ActionPerformed(evt);
            }
        });

        txtPokemon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemon1ActionPerformed(evt);
            }
        });

        jlImgPokemon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlImgPokemon1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel1.setText("VIDA:");

        javax.swing.GroupLayout jpPokemon1Layout = new javax.swing.GroupLayout(jpPokemon1);
        jpPokemon1.setLayout(jpPokemon1Layout);
        jpPokemon1Layout.setHorizontalGroup(
            jpPokemon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPokemon1Layout.createSequentialGroup()
                .addComponent(jlImgPokemon1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPokemon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPokemon1Layout.createSequentialGroup()
                        .addComponent(txtPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPokemon1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPokemonVida1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jpPokemon1Layout.setVerticalGroup(
            jpPokemon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPokemon1Layout.createSequentialGroup()
                .addComponent(txtPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPokemon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPokemonVida1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(jlImgPokemon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpPokemon2.setBackground(new java.awt.Color(255, 153, 102));

        txtPokemon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemon2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel9.setText("VIDA:");

        jlImgPokemon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlImgPokemon2MouseClicked(evt);
            }
        });

        txtPokemonVida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemonVida2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPokemon2Layout = new javax.swing.GroupLayout(jpPokemon2);
        jpPokemon2.setLayout(jpPokemon2Layout);
        jpPokemon2Layout.setHorizontalGroup(
            jpPokemon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPokemon2Layout.createSequentialGroup()
                .addComponent(jlImgPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jpPokemon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpPokemon2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPokemonVida2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jpPokemon2Layout.setVerticalGroup(
            jpPokemon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPokemon2Layout.createSequentialGroup()
                .addComponent(txtPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpPokemon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPokemonVida2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
            .addComponent(jlImgPokemon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpPokemon3.setBackground(new java.awt.Color(204, 0, 255));

        txtPokemon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemon3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel3.setText("VIDA:");

        txtPokemonVida3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemonVida3ActionPerformed(evt);
            }
        });

        jlImgPokemon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlImgPokemon3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpPokemon3Layout = new javax.swing.GroupLayout(jpPokemon3);
        jpPokemon3.setLayout(jpPokemon3Layout);
        jpPokemon3Layout.setHorizontalGroup(
            jpPokemon3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPokemon3Layout.createSequentialGroup()
                .addComponent(jlImgPokemon3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpPokemon3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPokemon3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtPokemon3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpPokemon3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPokemonVida3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jpPokemon3Layout.setVerticalGroup(
            jpPokemon3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPokemon3Layout.createSequentialGroup()
                .addComponent(txtPokemon3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPokemon3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPokemonVida3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jlImgPokemon3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpPokemon4.setBackground(new java.awt.Color(0, 153, 153));

        txtPokemon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemon4ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel10.setText("VIDA:");

        txtPokemonVida4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPokemonVida4ActionPerformed(evt);
            }
        });

        jlImgPokemon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlImgPokemon4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpPokemon4Layout = new javax.swing.GroupLayout(jpPokemon4);
        jpPokemon4.setLayout(jpPokemon4Layout);
        jpPokemon4Layout.setHorizontalGroup(
            jpPokemon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPokemon4Layout.createSequentialGroup()
                .addComponent(jlImgPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpPokemon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpPokemon4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPokemonVida4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jpPokemon4Layout.setVerticalGroup(
            jpPokemon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPokemon4Layout.createSequentialGroup()
                .addGroup(jpPokemon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPokemon4Layout.createSequentialGroup()
                        .addComponent(txtPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpPokemon4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtPokemonVida4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlImgPokemon4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LISTA DE POKEMONES:");

        jLabel2.setIcon(new javax.swing.ImageIcon("T:\\LP2\\Alejandro\\LP2\\LP2Draw\\res\\pokemon\\fondoPokemons2.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jpPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jpPokemon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jpPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jpPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jpPokemonSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jpPokemon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jpPokemon3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jpPokemon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jpPokemon4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jpPokemonSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(173, 173, 173))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPokemonVida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemonVida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemonVida1ActionPerformed

    private void txtPokemon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemon3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemon3ActionPerformed

    private void txtPokemon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemon2ActionPerformed

    private void txtPokemon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemon4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemon4ActionPerformed

    private void txtPokemonSNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemonSNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemonSNombreActionPerformed

    private void txtPokemon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemon1ActionPerformed

    private void txtPokemonVida3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemonVida3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemonVida3ActionPerformed

    private void txtPokemonSAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemonSAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemonSAtaqueActionPerformed

    private void txtPokemonSDefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemonSDefensaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemonSDefensaActionPerformed

    private void txtPokemonSVidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemonSVidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemonSVidaActionPerformed

    private void txtPokemonSTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemonSTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemonSTipoActionPerformed

    private void txtPokemonVida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemonVida2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemonVida2ActionPerformed

    private void txtPokemonVida4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPokemonVida4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPokemonVida4ActionPerformed

    private void jlImgPokemon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlImgPokemon1MouseClicked
        // TODO add your handling code here:
        Pokemon pok = listaPokemones.get(0+indice);
        txtPokemonSNombre.setText(pok.getName());
        txtPokemonSAtaque.setText(String.valueOf(pok.getAttack_pts()));
        txtPokemonSDefensa.setText(String.valueOf(pok.getDefense_pts()));
        txtPokemonSTipo.setText(String.valueOf(pok.getType()));
        txtPokemonSVida.setText(String.valueOf(pok.getLife()));
        String nombre = String.valueOf(pok.getId());
        String ruta = "res/pokemons/" + nombre+".png";
        //ImageIcon img1 = new ImageIcon(getClass().getResource(ruta));
        ImageIcon img1 = new ImageIcon(ruta);
        ImageIcon icono = new ImageIcon(img1.getImage().getScaledInstance(jlPokSelectedImg.getWidth(),jlPokSelectedImg.getHeight(), Image.SCALE_DEFAULT));
        jlPokSelectedImg.setIcon(icono);
        
    }//GEN-LAST:event_jlImgPokemon1MouseClicked

    private void jlImgPokemon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlImgPokemon2MouseClicked
        // TODO add your handling code here:
        Pokemon pok = listaPokemones.get(1+indice);
        txtPokemonSNombre.setText(pok.getName());
        txtPokemonSAtaque.setText(String.valueOf(pok.getAttack_pts()));
        txtPokemonSDefensa.setText(String.valueOf(pok.getDefense_pts()));
        txtPokemonSTipo.setText(String.valueOf(pok.getType()));
        txtPokemonSVida.setText(String.valueOf(pok.getLife()));
        String nombre = String.valueOf(pok.getId());
        String ruta = "res/pokemons/" + nombre+".png";
        //ImageIcon img1 = new ImageIcon(getClass().getResource(ruta));
        ImageIcon img1 = new ImageIcon(ruta);
        ImageIcon icono = new ImageIcon(img1.getImage().getScaledInstance(jlPokSelectedImg.getWidth(),jlPokSelectedImg.getHeight(), Image.SCALE_DEFAULT));
        jlPokSelectedImg.setIcon(icono);
    }//GEN-LAST:event_jlImgPokemon2MouseClicked

    private void jlImgPokemon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlImgPokemon3MouseClicked
        // TODO add your handling code here:
        Pokemon pok = listaPokemones.get(2+indice);
        txtPokemonSNombre.setText(pok.getName());
        txtPokemonSAtaque.setText(String.valueOf(pok.getAttack_pts()));
        txtPokemonSDefensa.setText(String.valueOf(pok.getDefense_pts()));
        txtPokemonSTipo.setText(String.valueOf(pok.getType()));
        txtPokemonSVida.setText(String.valueOf(pok.getLife()));
        String nombre = String.valueOf(pok.getId());
        String ruta = "res/pokemons/" + nombre+".png";
        //ImageIcon img1 = new ImageIcon(getClass().getResource(ruta));
        ImageIcon img1 = new ImageIcon(ruta);
        ImageIcon icono = new ImageIcon(img1.getImage().getScaledInstance(jlPokSelectedImg.getWidth(),jlPokSelectedImg.getHeight(), Image.SCALE_DEFAULT));
        jlPokSelectedImg.setIcon(icono);
        
    }//GEN-LAST:event_jlImgPokemon3MouseClicked

    private void jlImgPokemon4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlImgPokemon4MouseClicked
        // TODO add your handling code here:
        Pokemon pok = listaPokemones.get(3+indice);
        txtPokemonSNombre.setText(pok.getName());
        txtPokemonSAtaque.setText(String.valueOf(pok.getAttack_pts()));
        txtPokemonSDefensa.setText(String.valueOf(pok.getDefense_pts()));
        txtPokemonSTipo.setText(String.valueOf(pok.getType()));
        txtPokemonSVida.setText(String.valueOf(pok.getLife()));
        String nombre = String.valueOf(pok.getId());
        String ruta = "res/pokemons/" + nombre+".png";
        //ImageIcon img1 = new ImageIcon(getClass().getResource(ruta));
        ImageIcon img1 = new ImageIcon(ruta);
        ImageIcon icono = new ImageIcon(img1.getImage().getScaledInstance(jlPokSelectedImg.getWidth(),jlPokSelectedImg.getHeight(), Image.SCALE_DEFAULT));
        jlPokSelectedImg.setIcon(icono);
    }//GEN-LAST:event_jlImgPokemon4MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Pokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Pokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Pokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Pokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Pokemons().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlImgPokemon1;
    private javax.swing.JLabel jlImgPokemon2;
    private javax.swing.JLabel jlImgPokemon3;
    private javax.swing.JLabel jlImgPokemon4;
    private javax.swing.JLabel jlPokSelectedImg;
    private javax.swing.JPanel jpPokemon1;
    private javax.swing.JPanel jpPokemon2;
    private javax.swing.JPanel jpPokemon3;
    private javax.swing.JPanel jpPokemon4;
    private javax.swing.JPanel jpPokemonSelected;
    private javax.swing.JTextField txtPokemon1;
    private javax.swing.JTextField txtPokemon2;
    private javax.swing.JTextField txtPokemon3;
    private javax.swing.JTextField txtPokemon4;
    private javax.swing.JTextField txtPokemonSAtaque;
    private javax.swing.JTextField txtPokemonSDefensa;
    private javax.swing.JTextField txtPokemonSNombre;
    private javax.swing.JTextField txtPokemonSTipo;
    private javax.swing.JTextField txtPokemonSVida;
    private javax.swing.JTextField txtPokemonVida1;
    private javax.swing.JTextField txtPokemonVida2;
    private javax.swing.JTextField txtPokemonVida3;
    private javax.swing.JTextField txtPokemonVida4;
    // End of variables declaration//GEN-END:variables
}
